hydra:
  searchpath:
    - file://verl/trainer/config

defaults:
  - ppo_trainer
  - _self_

trainer:
  algo_mode: dora
  dora:
    objective: "2.4"
    delta: 6.0
    tau: 1.0
    beta: 1.0

actor_rollout_ref:
  model:
    path: /path/to/dora/model 
    external_lib: null
    override_config: {}
    enable_gradient_checkpointing: True
    use_remove_padding: False
    use_liger: False
    trust_remote_code: False
  nora:
    model:
      path: /path/to/nora/model
  ref:
    model:
      path: /path/to/ref/model
      external_lib: null
      override_config: {}
      enable_gradient_checkpointing: True
      use_remove_padding: False
      use_liger: False
      trust_remote_code: False